### ISSUE TITLE
Server error, image will be reloaded. That will not affect your records, sorry about the inconvenience.

### ISSUE THREAD

**Issue by aalvarezellacuria** [philadias/freelabel#12]
when entering in "From Scratch"
The message
"Server error, image will be reloaded. That will not affect your records, sorry about the inconvenience."
appears  after writting the dataset path, the name  and the output path
even when I  use the "DogDataset", 
Don't know how to fix it.
Thank you

**Comment by philadias** [comment]
Hi! I've just fixed an issue that might have caused the problem you've observed. You can either clone again the repo, or do the following:
- create a folder "lists", under "./static/lists"

If that does not fix it, please check if there is an error message in the terminal (where you launched the tool) and post it here so that we can take a closer look

Thanks!!

**Comment by aalvarezellacuria** [comment]
Thank you very much for the quick response, I have clone again the repo, and now it works.
